### ISSUE TITLE
ERROR CONNECTION - Banner sftp_client has no object

### ISSUE THREAD

**Issue by ghost** [AlexOrlek/sftp_py#1]
Hi,

I've got two issues :

paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

AttributeError: 'RemoteTransfer' object has no attribute 'sftp_client'
Could not establish SSH connection: Error reading SSH protocol banner

What is my problem, about configuration. In RemoteTransfert(host, username, port, password, key)

Is it possible to auto accpet banner, or remote cert ? 

Thanks.

**Comment by AlexOrlek** [comment]
Hi,

It might be an issue with your server - can you ssh ok? You could try other similar repos (e.g. https://github.com/marian-code/ssh-utilities) to see if it's a bug in my code or a general connection problem.

I could add a banner_timeout parameter as the link suggests:
https://stackoverflow.com/questions/25609153/paramiko-error-reading-ssh-protocol-banner

If you paste your code I'd be happy to check it

Thanks
Alex

**Comment by ghost** [comment]
Variable changed by *, i cann't provide credentials & name file 

from ftplib import FTP


ftp = FTP('*')
ftp.login(user='*, passwd='*')
ftp.dir()
ftp.nlst()

out = 'C:\'
with open(out, 'wb') as f:
    ftp.retrbinary('RETR ' + '[FILE]', f.write())

def grabFile():
    filename = '*'

    localfile = open(filename, 'wb')
    ftp.retrlines('RETR ' + filename, localfile.write(), 1024)
    ftp.retrbinary('RETR ' + filename, localfile.write(), 1024)

    ftp.quit()
    localfile.close()

#ftp.retrlines('LIST')
ftp.close()

**Comment by AlexOrlek** [comment]
closing for now - assuming this was an issue with the user's server, not a bug in the code
